kumgan/urls.py
from django.urls import path
from kumgan import views

app_name = 'kumgan'

urlpatterns = [
    path('', views.index, name="index"),
    path('home/', views.home, name="home"),
    path('check/', views.Check, name='check'),
    path('signup/', views.signup, name="signup"),
    path('signin/', views.signin, name="signin"),
    path('signout/', views.signout, name="signout"),
    path('booking/', views.BookingCreateView.as_view(), name='booking'),
    path('booking_view/', views.BookingView.as_view(), name='booking_view'),
    path('<int:pk>/booking_update', views.BookingUpdate.as_view(), name='booking_update'),
    path('box_create/', views.BoxCreate.as_view(), name='box_create'),
    path('box_list/', views.BoxListView.as_view(), name='box_list'),
    path('<int:pk>/box_update', views.BoxUpdateView.as_view(), name='box_update'),
    path('<int:pk>/box_delete', views.BoxDeleteView.as_view(), name='box_delete'),
    path('price_create/', views.PriceCreateView.as_view(), name='price_create'),
    path('price_list/', views.PriceListView.as_view(), name='price_list'),
    path('<int:pk>/price_update', views.PriceUpdateView.as_view(), name='price_update'),
    path('<int:pk>/price_delete', views.PriceDeleteView.as_view(), name='price_delete'),
    path('schedule_create/', views.ScheduleCreate.as_view(), name='schedule_create'),
    path('schedule_list/', views.ScheduleListView.as_view(), name='schedule_list'),
    path('<int:pk>/schedule_update', views.ScheduleUpdateView.as_view(), name='schedule_update'),
    path('<int:pk>/schedule_delete', views.ScheduleDeleteView.as_view(), name='schedule_delete'),
    path('category_create/', views.CategoryCreate.as_view(), name='category_create'),
    path('category_list/', views.CategoryListView.as_view(), name='category_list'),
    path('<int:pk>/category_update/', views.CategoryUpdateView.as_view(), name='category_update'),
    path('<int:pk>/category_delete/', views.CategoryDeleteView.as_view(), name='category_delete'),
    path('<int:pk>/delete_booking', views.BookingDeleteView.as_view(), name='delete_booking'),
    path('booking_view_staff/', views.BookingView_staff.as_view(), name='booking_view_staff'),
]

kumgan_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from kumgan_system import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kumgan.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_URL)

kumgan/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

now = timezone.now()


class Box(models.Model):
    number_of_box = models.SmallIntegerField(default=0)
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.number_of_box)

    def get_absolute_url(self):
        return '/box_list'

    class Meta:
        verbose_name = 'Box'
        verbose_name_plural = 'Boxes'


class Schedule(models.Model):
    time_date = models.DateTimeField(auto_now=False, auto_now_add=False, blank=False)
    box = models.ForeignKey(Box, on_delete=models.CASCADE, related_name='box')
    status = models.BooleanField(default=False)

    def __str__(self):
        return str(self.time_date)

    def get_box_box(self):
        return self.box.number_of_box

    def get_absolute_url(self):
        return '/schedule_list'

    class Meta:
        verbose_name = 'Schedule'
        verbose_name_plural = 'Schedules'


class Category_Transport(models.Model):
    type_of_car = models.CharField(max_length=20)

    def __str__(self):
        return self.type_of_car

    def get_absolute_url(self):
        return '/category_list'

    class Meta:
        verbose_name = 'Category_Transport'
        verbose_name_plural = 'Category_Transports'


class Services(models.Model):
    title_service = models.CharField(max_length=20)
    price_service = models.IntegerField(verbose_name='Цена')
    amount = models.IntegerField(default=1, verbose_name="Количество")
    category_transport = models.ForeignKey(Category_Transport,
                                           on_delete=models.CASCADE, related_name="category_transport")

    def __str__(self):
        return str(self.title_service)

    def get_name_of_service(self):
        return self.title_service

    def get_price(self):
        return self.price_service

    def get_total_item_price(self):
        return self.amount * self.get_price()

    def get_final_price(self):
        return self.get_total_item_price()

    def get_absolute_url(self):
        return '/price_list'

    class Meta:
        verbose_name = 'Service'
        verbose_name_plural = 'Services'


class Booking(models.Model):
    """Бронирование"""
    category_transport = models.ForeignKey(Category_Transport,
                                           on_delete=models.CASCADE, related_name="category_transport_booking")
    time_and_date = models.ForeignKey(Schedule, on_delete=models.CASCADE, related_name="time_and_date")
    title_service = models.ManyToManyField(Services, related_name="title_service_booking")
    number_car = models.CharField(max_length=6)
    status = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for i in self.title_service.all():
            total += i.get_final_price()
        return total

    def get_box(self):
        box = self.time_and_date.get_box_box()
        return box

    def get_service(self):
        service= ''
        for i in self.title_service.all():
            service = i.get_name_of_service()
        return service

    # def get_price_each(self):
    #     for i in self.title_service.all():
    #         price = i.get_total_item_price()
    #         return price

    def get_absolute_url(self):
        return '/home'

    class Meta:
        verbose_name = 'Booking'
        verbose_name_plural = 'Bookings'

kumgan/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Booking, Schedule, Box, Category_Transport, Services


class SigninForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))


class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email", "password1", "password2"]

        widgets = {
            "username": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Логин',
            }),
            "first_name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Имя',
            }),
            "last_name": forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Фамилия',
            }),
            "email": forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'gmail',
            }),
            "password1": forms.PasswordInput(attrs={
                'class': 'form-control',
                'placeholder': 'password',
            }),
        }


# ['category_transport', 'time_and_date', 'title_service', 'number_car', 'status']
class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['category_transport', 'time_and_date', 'title_service', 'number_car']


class BookingUpdateForm(forms.ModelForm):
    class Meta:
        model = Booking
        fields = ['status']


class BoxUpdateForm(forms.ModelForm):
    class Meta:
        model = Box
        fields = ('number_of_box', )


class ServicesUpdateForm(forms.ModelForm):
    class Meta:
        model = Services
        fields = ('title_service', 'price_service', 'category_transport',)


class ScheduleUpdateCreateForm(forms.ModelForm):
    class Meta:
        model = Schedule
        fields = ['time_date', 'box']

        widgets = {
            "time_date": forms.TextInput(attrs={'type': 'datetime-local'})
        }


class CategoryUpdateCreateForm(forms.ModelForm):
    class Meta:
        model = Category_Transport
        fields = ['type_of_car']

kumgan/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import SignupForm, SigninForm, BookingForm, BookingUpdateForm, BoxUpdateForm, ServicesUpdateForm, \
    ScheduleUpdateCreateForm, CategoryUpdateCreateForm
from .models import Booking, Schedule, Services, Box, Category_Transport
from django.core.exceptions import ObjectDoesNotExist
from django.views.generic import DeleteView, ListView, DetailView, UpdateView, CreateView


def index(request):
    if request.user.is_superuser:  # Владелец
        return redirect('admin/')
    else:
        return render(request, 'kumgan/index.html')


def Check(request):
    try:
        da = Booking.objects.filter(user=request.user.id)[:1]
        data = Booking.objects.filter(user_id=request.user).last()
        context = {
            'data': data,
            'da': da
        }
        return render(request, 'kumgan/check.html', context)
    except ObjectDoesNotExist:
        messages.warning(request, "Ошибка")
        return redirect("/home")


class BookingDeleteView(DeleteView):
    model = Booking
    success_url = '/home'
    template_name = 'kumgan/delete_booking.html'


def home(request):
    data = Booking.objects.filter(user_id=request.user)[:1]

    if request.user.is_superuser:  # Владелец
        return redirect('admin/')
    elif request.user.is_authenticated:
        return render(request, 'kumgan/home.html', {'data': data})
    else:
        return render(request, 'kumgan/index.html')


# def Booking_create(request):
#     error = ''
#     if request.method == "POST":
#         form = BookingForm(request.POST)
#         if form.is_valid():
#             booking = form.save(commit=False)
#             booking.user = request.user
#             booking.status = False
#             booking.save()
#             print('success booking')
#             return redirect('kumgan:check')
#         else:
#             messages.error(request, "Error in form")
#     form = BookingForm()
#     data = {
#         'forms': form,
#         'error': error,
#     }
#     return render(request, 'kumgan/booking.html', data)


class BookingCreateView(CreateView):
    fields = ['category_transport', 'time_and_date', 'title_service', 'number_car']
    template_name = 'kumgan/booking.html'

    def get_queryset(self):
        """Return the last five published questions."""
        return Booking.objects.all()

    def post(self, request, *args, **kwargs):
        form = BookingForm(request.POST)
        if form.is_valid():
            booking = form.save(commit=False)
            booking.user = self.request.user
            booking.status = False
            booking.save()
            return redirect('kumgan:check')
        return render(request, 'kumgan/booking.html', {'form': form})


class BookingView(ListView):
    model = Booking
    template_name = 'kumgan/booking_view.html'


class BookingView_staff(ListView):
    model = Booking
    template_name = 'kumgan/booking_view_staff.html'


class PriceCreateView(CreateView):
    model = Services
    template_name = 'kumgan/price_create.html'
    fields = ['title_service', 'price_service', 'category_transport']


class PriceListView(ListView):
    model = Services
    template_name = 'kumgan/price_list.html'


class PriceDeleteView(DeleteView):
    model = Services
    template_name = 'kumgan/price_delete.html'
    success_url = '/price_list'


class PriceUpdateView(UpdateView):
    model = Services
    template_name = 'kumgan/price_update.html'
    form_class = ServicesUpdateForm


class BoxCreate(CreateView):
    model = Box
    template_name = 'kumgan/box_create.html'
    fields = ['number_of_box']


class BoxListView(ListView):
    model = Box
    template_name = 'kumgan/box_list.html'


class BoxUpdateView(UpdateView):
    model = Box
    template_name = 'kumgan/box_update.html'
    form_class = BoxUpdateForm


class BoxDeleteView(DeleteView):
    model = Box
    template_name = 'kumgan/box_delete.html'
    success_url = '/box_list'


class CategoryCreate(CreateView):
    model = Category_Transport
    template_name = 'kumgan/category_create.html'
    fields = ['type_of_car']


class CategoryListView(ListView):
    model = Category_Transport
    template_name = 'kumgan/category_list.html'


class CategoryUpdateView(UpdateView):
    model = Category_Transport
    template_name = 'kumgan/category_update.html'
    form_class = CategoryUpdateCreateForm


class CategoryDeleteView(DeleteView):
    model = Category_Transport
    template_name = 'kumgan/box_delete.html'
    success_url = '/category_list'


class BookingUpdate(UpdateView):
    model = Booking
    template_name = 'kumgan/booking_update.html'
    form_class = BookingUpdateForm


class ScheduleCreate(CreateView):
    model = Schedule
    template_name = 'kumgan/schedule_create.html'
    form_class = ScheduleUpdateCreateForm


class ScheduleListView(ListView):
    model = Schedule
    template_name = 'kumgan/schedule_list.html'


class ScheduleUpdateView(UpdateView):
    model = Schedule
    template_name = 'kumgan/schedule_update.html'
    form_class = ScheduleUpdateCreateForm


class ScheduleDeleteView(DeleteView):
    model = Schedule
    template_name = 'kumgan/schedule_delete.html'
    success_url = '/schedule_list'


def signup(request):
    if request.method == "POST":
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, "User saved")
            return redirect("kumgan:signin")
        else:
            messages.error(request, "Error in form")
    else:
        form = SignupForm()
    context = {"form": form}
    return render(request, "kumgan/signup.html", context)


def signin(request):
    if request.method == "POST":
        form = SigninForm(request.POST)
        username = form["username"].value()
        password = form["password"].value()
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            messages.success(request, "Successfully logged in")
            print("Successfully logged in")
            if request.user.is_superuser:  # Владелец
                return redirect('kumgan:index')
            return redirect('kumgan:home')
        else:
            print("Invalid Username or Password")
            messages.error(request, "Invalid Username or Password")
    else:
        form = SigninForm()
    context = {"form": form}
    return render(request, "kumgan/signin.html", context)


def signout(request):
    logout(request)
    return redirect("kumgan:signin")

kumgan/templates/kumgan/admin.html
{% extends 'kumgan/base.html' %}
{% load static %}

{% block title %} Kumgan {% endblock title %}

{% block content %}
Hello admin
{%  endblock content %}

kumgan/templates/kumgan/box_delete.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-2 title_of_page">Удалить Бокс</h2>
    </div>
    </span>
{% endblock title_page %}

{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4></a>
        <a href="{% url 'kumgan:home'%}" class="col-6">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:box_list' %}" type="button" class="btn btn-outline-success col-2">Боксы</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-danger text-center w-50 m-5">
                              Удалить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/box_update.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-3 title_of_page">Обновить Бокс</h2>
    </div>
    </span>
{% endblock title_page %}
{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4> </a>
        <a href="{% url 'kumgan:home'%}" class="col-5">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:box_list' %}" type="button" class="btn btn-outline-success col-2">Боксы</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col">{{ form.number_of_box | as_crispy_field }}</div>
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-success text-center w-50 m-5">
                              Обновить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/category_create.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-3 title_of_page">Создать категорию транспорта</h2>
    </div>
    </span>
{% endblock title_page %}
{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4> </a>
        <a href="{% url 'kumgan:home'%}" class="col-5">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:category_list' %}" type="button" class="btn btn-outline-success col-2">Категории</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12">{{ form.type_of_car| as_crispy_field}}</div>
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-success text-center w-50 m-5">
                                Создать
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/category_update.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-3 title_of_page">Обновить категорию транспорта</h2>
    </div>
    </span>
{% endblock title_page %}
{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4> </a>
        <a href="{% url 'kumgan:home'%}" class="col-5">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:category_list' %}" type="button" class="btn btn-outline-success col-2">Категорию</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12">{{ form.type_of_car| as_crispy_field}}</div>
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-success text-center w-50 m-5">
                                Обновить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/home.html
{% extends 'kumgan/base.html' %}
{% load static %}
{% block title %} Kumgan {% endblock title %}
{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center ">
        <h1 class="col-1 title_of_page">Меню</h1>
    </div>
    </span>
{% endblock title_page %}


{% block content %}
<main class="container p-4">
<div class="row justify-content-evenly">
    {% if user.is_staff  %}
        <a href="{% url 'kumgan:booking_view' %}" class="col-4 p-2">
            <div class="card border_time_date_card" style="width: 18rem;">
                <img src="{% static 'kumgan/images/booking.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h2 class="card-title text-center title_of_page">Бронирования</h2>
                </div>
            </div>
        </a>

          <a href="{% url 'kumgan:box_create' %}" class="col-4 p-2">
            <div class="card border_time_date_card" style="width: 18rem;">
                <img src="{% static 'kumgan/images/box.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h2 class="card-title text-center title_of_page">Боксы</h2>
                </div>
            </div>
        </a>
          <a href="{% url 'kumgan:price_create' %}" class="col-4 p-2">
            <div class="card border_time_date_card" style="width: 18rem;">
                <img src="{% static 'kumgan/images/price.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h2 class="card-title text-center title_of_page">Прайс лист</h2>
                </div>
            </div>
        </a>


          <a href="{% url 'kumgan:schedule_create' %}" class="col-4 p-2">
            <div class="card border_time_date_card" style="width: 18rem;">
                <img src="{% static 'kumgan/images/schedule.png' %}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h2 class="card-title text-center title_of_page">Расписание</h2>
                </div>
            </div>
        </a>
        <a href="{% url 'kumgan:category_create' %}" class="col-4 p-2 text-center">
            <div class="card border_time_date_card  text-center" style="width: 18rem;">
                <img src="{% static 'kumgan/images/category.png' %}" class="card-img-top text-center" alt="...">
                <div class="card-body text-center">
                    <h2 class="card-title text-center title_of_page">Категории</h2>
                </div>
            </div>
        </a>

 {#  ----------------------------------------------------------------------------------------------      #}
        {% elif perms.kumgan.add_box %}
       <a href="{% url 'kumgan:booking_view_staff' %}" class="col-3">
                <div class="card border_time_date_card" style="width: 18rem;">
                    <img src="{% static 'kumgan/images/booking.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h2 class="card-title text-center title_of_page">Бронирования</h2>
                    </div>
                </div>
            </a>
{#  ----------------------------------------------------------------------------------------------      #}

    {% elif user.is_authenticated %}
            <a href="{% url 'kumgan:booking' %}" class="col-3">
                <div class="card border_time_date_card" style="width: 18rem;">
                    <img src="{% static 'kumgan/images/booking.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h2 class="card-title text-center title_of_page">Бронировать</h2>
                    </div>
                </div>
            </a>
            <a href="{% url 'kumgan:check' %}" class="col-3">
                <div class="card border_time_date_card" style="width: 18rem;">
                    <img src="{% static 'kumgan/images/check.png' %}" class="card-img-top" alt="check">
                    <div class="card-body ">
                        <h2 class="card-title  title_of_page">Чек</h2>
                    </div>
                </div>
            </a>
     {% endif %}
</div>
</main>
{%  endblock content %}

kumgan/templates/kumgan/price_create.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-3 title_of_page">Создать Услугу</h2>
    </div>
    </span>
{% endblock title_page %}
{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4> </a>
        <a href="{% url 'kumgan:home'%}" class="col-5">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:price_list' %}" type="button" class="btn btn-outline-success col-2">Услуги</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-12">{{ form.title_service | as_crispy_field }}</div>
                            <div class="col-12">{{ form.price_service | as_crispy_field }}</div>
                            <div class="col-12">{{ form.category_transport | as_crispy_field }}</div>
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-success text-center w-50 m-5">
                                Создать
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/price_delete.html
{% extends 'kumgan/base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block title_page %}
    <span class="container">
    <div class="row text-center justify-content-center">
        <h2 class="col-2 title_of_page">Удалить Услугу</h2>
    </div>
    </span>
{% endblock title_page %}
{% block header %}
<header class="header_bg">
<span class="container">
    <div class="row text-center justify-content-center align-items-center">
        <a class="col-2" href="{% url 'kumgan:signout' %}">
        <h4>Выйти</h4></a>
        <a href="{% url 'kumgan:home'%}" class="col-6">
           <img src="{% static 'kumgan/images/header_logo.png' %}" height="150px" alt="logo"/>
        </a>
         <a href="{% url 'kumgan:price_list' %}" type="button" class="btn btn-outline-success col-2">Услуги</a>
        <h3 class="col-2">{{user.get_username}}</h3>
    </div>
</span>
</header>
{% endblock header %}

{% block content %}
    <div class="container pt-5 ">
        <div class="row justify-content-center text-center">
            <div class="col-4 border_time_date_card">
                <form class="pt-5" method="post">
                    {% csrf_token %}
                    <div class="container">
                        <div class="row justify-content-center">
                            <button id="button_index" type="submit"
                                    class="btn btn-outline-danger text-center w-50 m-5">
                              Удалить
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

{%  endblock content %}

kumgan/templates/kumgan/staff.html
{% extends 'kumgan/base.html' %}
{% load static %}

{% block title %} Kumgan staff {% endblock title %}

{% block content %}
Hello staff
{%  endblock content %}